# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version:  2.1
orbs:
  go: circleci/go@1.7.0
  codecov: codecov/codecov@1.0.4
jobs:
  test:
    executor:
      name: go/default
      tag: '1.14'
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run:  mkdir -p /tmp/test-result
      - go/test:
          coverprofile: /tmp/test-result/cover.out
          verbose:  true
      - codecov/upload:
          file: /tmp/test-result/cover.out
  build:
    executor:
      name: go/default
      tag:  '1.14'
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run:  mkdir -p /tmp/artifact
      - run:  go build -o /tmp/artifact/main main.go
      - store_artifacts:
          path: /tmp/artifact/main


workflows:
  main:
    jobs:
      - test:
          context:  CODECOV
      - build:
          requires:
              - test
      # - codecov-update:
      #     context:  CODECOV
      #     requires:
      #       - test