version: "3"
services:
  nginx:
      image:  nginx
      volumes: 
        - ./nginx:/etc/nginx/conf.d
      ports:
        - 80:80
      depends_on: 
        - app
  app:
    image: danish9966/todo-app
    environment: 
      - POSTGRES_HOST=db
    depends_on: 
      - db
  db:
    image:  postgres:12.6
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    ports:
        - 5432:5432
    volumes: 
        - ./sql:/docker-entrypoint-initdb.d
#   pg_admin:
#     image:  dpage/pgadmin4:5.4
#     environment: 
#         - PGADMIN_DEFAULT_EMAIL=pgadmin@example.com
#         - PGADMIN_DEFAULT_PASSWORD=password
#     ports: 
#         -  8081:80