version: "3"
services:
  nginx:
      image:  nginx
      volumes: 
        - ./nginx:/etc/nginx/conf.d
      ports:
        - 80:80
      depends_on: 
        - app
  app:
    image: danish9966/todo-app:latest
    environment: 
      - POSTGRES_HOST=db
      # - ELASTIC_APM_SERVER_URL=http://x.x.x.x:8200
      # - ELASTIC_APM_LOG_FILE=stderr
      # - ELASTIC_APM_LOG_LEVEL=debug
      # - ENABLE_ELASTIC_APM=true
    depends_on: 
      - db
  
  db:
    image:  postgres:12.6
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    ports:
        - 5432:5432
    volumes: 
        - ./sql:/docker-entrypoint-initdb.d
